# Generated by Django 4.2.3 on 2023-07-23 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialapp', '0002_remove_post_images_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedislike',
            name='status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_by',
        ),
        migrations.AddField(
            model_name='likedislike',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='likedislike',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
