# Generated by Django 4.2.3 on 2023-07-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0004_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
